# Use an official Python runtime as a parent image
FROM python:3.10

# Set the working directory inside the container
WORKDIR /code

# Install system dependencies
RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc \
       python3-dev \
       sqlite3 \
       libpq-dev \
       pkg-config \
       default-libmysqlclient-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy the requirements file first
COPY requirements.txt /code/

# Install Python dependencies
RUN pip install --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy the API Gateway code into the container
COPY . /code/

# Copy db.json into the container (optional if you prefer volume mounting)
#COPY db.json /code/data/


EXPOSE 8050

# Run the API Gateway service (you can also include initialization commands here if needed)
CMD ["python", "manage.py", "runserver", "0.0.0.0:8050"]
