version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./static:/code/static
      - ./conf.d:/etc/nginx/conf.d
    depends_on:
      - farm

    environment:
      - SERVER_IP=${SERVER_IP}
  farm:
    build:
      context: .
      dockerfile: dockerfile.farm
    ports:
      - "8050:8050"

    environment:
      - SERVER_IP=${SERVER_IP}
