version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: dockerfile.nginx
    container_name: nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
      - ./myapp.conf:/etc/nginx/conf.d/myapp.conf
      - ./staticfiles:/code/staticfiles  # This should map to where collectstatic places your files
      - ./media:/code/media  # If you have media files, map this as well
      - ./templates:/code/templates
    depends_on:
      - farm
    environment:
      - SERVER_IP=${SERVER_IP}

  farm:
    build:
      context: .
      dockerfile: dockerfile.farm
    container_name: farm
    image: farm
 #   volumes:
 #     - ./static:/code/static  # Local static files for development, optional
#      - ./templates:/code/templates  # Local templates for development, optional
    ports:
      - "8050:8050"
    environment:
      - SERVER_IP=${SERVER_IP}

