# Generated by Django 5.0.2 on 2024-07-31 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='chemical',
            name='associated_products',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='usage_instructions',
            field=models.TextField(default=5443),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ChemicalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateField()),
                ('result', models.TextField(blank=True, null=True)),
                ('is_preventative', models.BooleanField(default=False)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_tracker.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended_date', models.DateField()),
                ('reason', models.TextField()),
                ('result', models.TextField(blank=True, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_tracker.chemical')),
            ],
        ),
    ]
