# Generated by Django 5.0.2 on 2024-07-31 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_tracker', '0002_remove_chemical_purchase_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='illness',
            field=models.CharField(default=5546, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recommendation',
            name='plant',
            field=models.CharField(default=44556, max_length=100),
            preserve_default=False,
        ),
    ]
