# Generated by Django 5.0.2 on 2024-08-01 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_tracker', '0004_recommendation_minor_result_recommendation_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='duration_days',
            field=models.PositiveIntegerField(default=3345, help_text='Duration of the treatment in days'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treatment',
            name='is_preventative',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='treatment',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatment',
            name='times_per_week',
            field=models.PositiveIntegerField(default=233232, help_text='Number of times per week the treatment is applied'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChemicalApplication',
        ),
    ]
