# Generated by Django 5.0.2 on 2024-08-02 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_tracker', '0005_treatment_duration_days_treatment_is_preventative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('details', models.TextField()),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemical_tracker.treatment')),
            ],
        ),
    ]
