# Generated by Django 5.0.2 on 2024-08-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemical_tracker', '0008_remove_treatment_final_result_finalresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalresult',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
