# Generated by Django 5.0.2 on 2024-07-31 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logbook', '0003_expense_quantity_sale_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
