# Generated by Django 5.0.2 on 2024-07-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SoilCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pH', models.DecimalField(decimal_places=2, max_digits=4)),
                ('moisture', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CropSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=100)),
                ('season', models.CharField(max_length=100)),
                ('soil_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planting.soilcondition')),
            ],
        ),
    ]
